version: "3"

services:
  adopt-service:
    image: jenkins:5000/adopt-service
    restart: always
    ports:
    - 8182:8182
    depends_on:
    - mysql-server

  user-management:
    image: jenkins:5000/user-management
    restart: always
    ports:
    - 8181:8181
    depends_on:
    - mysql-server

  mysql-server:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: devopz
      MYSQL_USER: devopz
      MYSQL_PASSWORD: changeme      
    volumes:
    - /opt/cihanca-devopz/data:/var/lib/mysql
    ports:
    - 3306:3306

  nginx:
    image: nginx
    restart: always
    ports:
    - 80:80
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro      
    depends_on:
    - adopt-service
    - user-management

  