version: "3"

services:
  adopt-service:
    image: jenkins:5000/adopt-service
    restart: always
    ports:
      - 8182:8182
    deploy:
      replicas: 2      

  user-management:
    image: jenkins:5000/user-management
    restart: always
    ports:
      - 8181:8181

  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro      

  