version: "3"

services:
  adopt-service:
    image: jenkins:5000/adopt-service
    restart: always
    depends_on:
    - mysql-server

  user-management:
    image: jenkins:5000/user-management
    restart: always
    depends_on:
    - mysql-server

  mysql-server:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: devopz
      MYSQL_USER: devopz
      MYSQL_PASSWORD: changeme   
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"   
    volumes:
    - /opt/cihanca-devopz/data:/var/lib/mysql

  nginx:
    image: nginx
    restart: always
    ports:
    - 80:80
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro      
    depends_on:
    - adopt-service
    - user-management

  