server:
  servlet:
    context-path: /api/adopt
  port: 8182

database: h2

spring:
  application:
    name: adopt-service
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        jdbc:
          time_zone: UTC
