server:
  port: 8181

spring:
  application:
    name: user-management
  datasource:
    url: jdbc:mysql://mysql-server:3306/devopz
    username: devopz
    password: changeme
    hikari:
      maximum-pool-size: 10    
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        jdbc:
          time_zone: UTC
