server:
  port: 8181

database: h2

spring:
  application:
    name: user-management
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        jdbc:
          time_zone: UTC
